name: Build Android APK

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: ui-automator-agent-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: ui-automator-agent-release
        path: app/build/outputs/apk/release/app-release.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: UI Automator Agent v${{ github.run_number }}
        body: |
          ## UI Automator Agent APK
          
          **Features:**
          - Auto-start service on boot
          - HTTP server on port 6790 (Appium WebDriver API)
          - HTTP server on port 7912 (UIAutomator2 JSON-RPC API)
          - Compatible with Zrok tunneling
          - No ADB required after installation
          
          **Installation:**
          1. Download `app-release.apk`
          2. Install on Android device (enable "Unknown sources")
          3. APK will auto-start service after boot
          4. Use with Zrok: `zrok share tcp 6790 --public`
          
          **API Endpoints:**
          - Appium: `https://your-zrok-url.zrok.net/wd/hub/status`
          - UIAutomator2: `https://your-zrok-url.zrok.net/info`
        files: |
          app/build/outputs/apk/debug/app-debug.apk
          app/build/outputs/apk/release/app-release.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
